/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ClassesTab: typeof import('./src/components/ClassesTab.vue')['default']
    Clock: typeof import('./src/components/clock/Clock.vue')['default']
    copy: typeof import('./src/components/HelloWorld copy.vue')['default']
    Digit: typeof import('./src/components/clock/Digit.vue')['default']
    Dots: typeof import('./src/components/Dots.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/pages/Home.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    HomeTab: typeof import('./src/components/HomeTab.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    Rays: typeof import('./src/components/Rays.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
    Settings: typeof import('./src/components/pages/Settings.vue')['default']
    SettingsPage: typeof import('./src/components/pages/SettingsPage.vue')['default']
    TabContent: typeof import('./src/components/TabContent.vue')['default']
    Weather: typeof import('./src/components/Weather.vue')['default']
  }
}
