/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationsSwitcher: typeof import('./src/components/AnimationsSwitcher.vue')['default']
    Clock: typeof import('./src/components/clock/Clock.vue')['default']
    Digit: typeof import('./src/components/clock/Digit.vue')['default']
    DivisionButton: typeof import('./src/components/DivisionButton.vue')['default']
    Divisions: typeof import('./src/components/pages/Divisions.vue')['default']
    Home: typeof import('./src/components/pages/Home.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    Overlay: typeof import('./src/components/Overlay.vue')['default']
    RoomButton: typeof import('./src/components/RoomButton.vue')['default']
    Rooms: typeof import('./src/components/pages/Rooms.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
    Settings: typeof import('./src/components/pages/Settings.vue')['default']
    TeacherButton: typeof import('./src/components/TeacherButton.vue')['default']
    Teachers: typeof import('./src/components/pages/Teachers.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Weather: typeof import('./src/components/Weather.vue')['default']
  }
}
