// common/messages/embed.go

// Package messages carries the generated S99Locale catalogs and the accessors
// that read them. Everything here except this file is generated by loc from
// i18n/locales and is never hand-edited.
package messages

import (
	"embed"
	"encoding/json"
	"os"
	"strings"

	"github.com/nicksnyder/go-i18n/v2/i18n"
	"golang.org/x/text/language"
)

// DefaultLanguage is what a caller gets when it asks for a language this
// server has no catalog for.
const DefaultLanguage = "en"

// Files holds the catalogs the logger and the command line read.
//
//go:embed locales/*.json
var Files embed.FS

// Names are the catalog files, for a caller that has to hand them to another
// package rather than read them here.
var Names = []string{"locales/en.json", "locales/pl.json"}

// bundle is built once: parsing every catalog per message would cost more than
// the whole render.
var bundle = newBundle()

func newBundle() *i18n.Bundle {
	built := i18n.NewBundle(language.English)
	built.RegisterUnmarshalFunc("json", json.Unmarshal)
	for _, name := range Names {
		// A catalog that does not parse is a build problem, not a runtime one:
		// it is generated and embedded, so it is the same bytes every run.
		if _, err := built.LoadMessageFileFS(Files, name); err != nil {
			panic("messages: load " + name + ": " + err.Error())
		}
	}
	return built
}

// Localizer resolves messages in one language, falling back to the default
// when this server carries no catalog for it.
func Localizer(lang string) *i18n.Localizer {
	if lang == "" {
		lang = DefaultLanguage
	}
	return i18n.NewLocalizer(bundle, lang, DefaultLanguage)
}

// LanguageFromEnv is what a program with no configuration file renders in:
// GOPTIVUM_LANG, then the shell's own locale, then the default.
func LanguageFromEnv() string {
	for _, name := range []string{"GOPTIVUM_LANG", "LC_ALL", "LC_MESSAGES", "LANG"} {
		value := strings.TrimSpace(os.Getenv(name))
		if value == "" {
			continue
		}
		// A shell writes pl_PL.UTF-8; a catalog is named for the language.
		value, _, _ = strings.Cut(value, ".")
		value, _, _ = strings.Cut(value, "@")
		if strings.EqualFold(value, "C") || strings.EqualFold(value, "POSIX") {
			return DefaultLanguage
		}
		value, _, _ = strings.Cut(value, "_")
		return strings.ToLower(value)
	}
	return DefaultLanguage
}

// Localize resolves one key by its string, for a caller that holds an id
// rather than an accessor. A key with no message renders as itself, which is
// visibly wrong rather than blank.
func Localize(localizer *i18n.Localizer, key string) string {
	rendered, err := localizer.Localize(&i18n.LocalizeConfig{MessageID: key})
	if err != nil {
		return key
	}
	return rendered
}
