// Code generated by loc. DO NOT EDIT.

package messages

import "github.com/nicksnyder/go-i18n/v2/i18n"

// zeroKey is the sub-key the opt-in zero band is written under.
//
// go-i18n selects by CLDR rule, and no rule returns "zero" for the locales we
// target: Polish resolves a count of 0 to Many. So the zero band is a separate
// message, reached only by the branch in the accessors below.
const zeroKey = ".zero"

func plain(l *i18n.Localizer, id string) string {
	out, err := l.Localize(&i18n.LocalizeConfig{MessageID: id})
	if err != nil {
		// The raw key is visibly wrong; an empty string reads as a blank label.
		return id
	}
	return out
}

func withData(l *i18n.Localizer, id string, data map[string]any) string {
	out, err := l.Localize(&i18n.LocalizeConfig{MessageID: id, TemplateData: data})
	if err != nil {
		return id
	}
	return out
}

func withCount(l *i18n.Localizer, id string, count int, data map[string]any) string {
	out, err := l.Localize(&i18n.LocalizeConfig{
		MessageID:    id,
		TemplateData: data,
		PluralCount:  count,
	})
	if err != nil {
		return id
	}
	return out
}

func zeroForm(l *i18n.Localizer, id string, data map[string]any) string {
	out, err := l.Localize(&i18n.LocalizeConfig{MessageID: id + zeroKey, TemplateData: data})
	if err != nil {
		return withCount(l, id, 0, data)
	}
	return out
}

// CliCommandAddrFlag Address flag description.
func CliCommandAddrFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.addrFlag")
}

// CliCommandCommands Cobra command list heading.
func CliCommandCommands(l *i18n.Localizer) string {
	return plain(l, "cli.command.commands")
}

// CliCommandCompletionShort Completion command summary.
func CliCommandCompletionShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.completionShort")
}

// CliCommandConfigFailed Configuration load failure with original diagnostic.
type CliCommandConfigFailedParams struct {
	Detail string
}

func CliCommandConfigFailed(l *i18n.Localizer, p CliCommandConfigFailedParams) string {
	data := map[string]any{
		"Detail": p.Detail,
	}
	return withData(l, "cli.command.configFailed", data)
}

// CliCommandConfigFlag Configuration flag description.
func CliCommandConfigFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.configFlag")
}

// CliCommandError CLI error line; detail is the diagnostic.
type CliCommandErrorParams struct {
	Detail string
}

func CliCommandError(l *i18n.Localizer, p CliCommandErrorParams) string {
	data := map[string]any{
		"Detail": p.Detail,
	}
	return withData(l, "cli.command.error", data)
}

// CliCommandFlags Cobra local flags heading.
func CliCommandFlags(l *i18n.Localizer) string {
	return plain(l, "cli.command.flags")
}

// CliCommandGlobalFlags Cobra inherited flags heading.
func CliCommandGlobalFlags(l *i18n.Localizer) string {
	return plain(l, "cli.command.globalFlags")
}

// CliCommandHelpFlag Help flag description.
func CliCommandHelpFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.helpFlag")
}

// CliCommandHelpHint Cobra help footer; command is the help invocation.
type CliCommandHelpHintParams struct {
	Command string
}

func CliCommandHelpHint(l *i18n.Localizer, p CliCommandHelpHintParams) string {
	data := map[string]any{
		"Command": p.Command,
	}
	return withData(l, "cli.command.helpHint", data)
}

// CliCommandHelpShort Help command summary.
func CliCommandHelpShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.helpShort")
}

// CliCommandInvalidFlag Usage error with the original parser diagnostic in detail.
type CliCommandInvalidFlagParams struct {
	Detail string
}

func CliCommandInvalidFlag(l *i18n.Localizer, p CliCommandInvalidFlagParams) string {
	data := map[string]any{
		"Detail": p.Detail,
	}
	return withData(l, "cli.command.invalidFlag", data)
}

// CliCommandInvalidLanguage Language validation error.
func CliCommandInvalidLanguage(l *i18n.Localizer) string {
	return plain(l, "cli.command.invalidLanguage")
}

// CliCommandLangFlag Language flag description; backticks name the value in Cobra help.
func CliCommandLangFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.langFlag")
}

// CliCommandLoggingFailed Logger setup failure with original diagnostic.
type CliCommandLoggingFailedParams struct {
	Detail string
}

func CliCommandLoggingFailed(l *i18n.Localizer, p CliCommandLoggingFailedParams) string {
	data := map[string]any{
		"Detail": p.Detail,
	}
	return withData(l, "cli.command.loggingFailed", data)
}

// CliCommandNoArgs Usage error; command takes no positional arguments.
type CliCommandNoArgsParams struct {
	Command string
}

func CliCommandNoArgs(l *i18n.Localizer, p CliCommandNoArgsParams) string {
	data := map[string]any{
		"Command": p.Command,
	}
	return withData(l, "cli.command.noArgs", data)
}

// CliCommandNoColorFlag Log color flag description.
func CliCommandNoColorFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.noColorFlag")
}

// CliCommandNoDescriptionsFlag Shell completion flag description.
func CliCommandNoDescriptionsFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.noDescriptionsFlag")
}

// CliCommandRootLong Server command description.
func CliCommandRootLong(l *i18n.Localizer) string {
	return plain(l, "cli.command.rootLong")
}

// CliCommandRootShort Server command summary.
func CliCommandRootShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.rootShort")
}

// CliCommandServeShort Serve command summary.
func CliCommandServeShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.serveShort")
}

// CliCommandShellShort Shell completion summary; shell is the shell name.
type CliCommandShellShortParams struct {
	Shell string
}

func CliCommandShellShort(l *i18n.Localizer, p CliCommandShellShortParams) string {
	data := map[string]any{
		"Shell": p.Shell,
	}
	return withData(l, "cli.command.shellShort", data)
}

// CliCommandStatusLong Status command description.
func CliCommandStatusLong(l *i18n.Localizer) string {
	return plain(l, "cli.command.statusLong")
}

// CliCommandStatusShort Status command summary.
func CliCommandStatusShort(l *i18n.Localizer) string {
	return plain(l, "cli.command.statusShort")
}

// CliCommandUnknownCommand Usage error; command is the unrecognized argument.
type CliCommandUnknownCommandParams struct {
	Command string
}

func CliCommandUnknownCommand(l *i18n.Localizer, p CliCommandUnknownCommandParams) string {
	data := map[string]any{
		"Command": p.Command,
	}
	return withData(l, "cli.command.unknownCommand", data)
}

// CliCommandUsage Cobra usage heading.
func CliCommandUsage(l *i18n.Localizer) string {
	return plain(l, "cli.command.usage")
}

// CliCommandVerboseFlag Verbose flag description.
func CliCommandVerboseFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.verboseFlag")
}

// CliCommandVersion Version output; release, api and client are version identifiers.
type CliCommandVersionParams struct {
	Api     string
	Client  string
	Release string
}

func CliCommandVersion(l *i18n.Localizer, p CliCommandVersionParams) string {
	data := map[string]any{
		"Api":     p.Api,
		"Client":  p.Client,
		"Release": p.Release,
	}
	return withData(l, "cli.command.version", data)
}

// CliCommandVersionFlag Version flag description.
func CliCommandVersionFlag(l *i18n.Localizer) string {
	return plain(l, "cli.command.versionFlag")
}

// CliProbeAttribute Tree table column: one attribute name.
func CliProbeAttribute(l *i18n.Localizer) string {
	return plain(l, "cli.probe.attribute")
}

// CliProbeAttributes Census table column: the attribute names that element carries.
func CliProbeAttributes(l *i18n.Localizer) string {
	return plain(l, "cli.probe.attributes")
}

// CliProbeBytes A size in bytes; size is the number.
type CliProbeBytesParams struct {
	Size string
}

func CliProbeBytes(l *i18n.Localizer, p CliProbeBytesParams) string {
	data := map[string]any{
		"Size": p.Size,
	}
	return withData(l, "cli.probe.bytes", data)
}

// CliProbeCompressed Probe field label: whether the payload was compressed in the container.
func CliProbeCompressed(l *i18n.Localizer) string {
	return plain(l, "cli.probe.compressed")
}

// CliProbeContainer Probe field label: the size of the file on disk.
func CliProbeContainer(l *i18n.Localizer) string {
	return plain(l, "cli.probe.container")
}

// CliProbeCount Census table column: how many of them the document holds.
func CliProbeCount(l *i18n.Localizer) string {
	return plain(l, "cli.probe.count")
}

// CliProbeElement Census table column: the element name.
func CliProbeElement(l *i18n.Localizer) string {
	return plain(l, "cli.probe.element")
}

// CliProbeElements Census summary label: how many distinct elements were found.
func CliProbeElements(l *i18n.Localizer) string {
	return plain(l, "cli.probe.elements")
}

// CliProbeFile Probe field label: the file being read.
func CliProbeFile(l *i18n.Localizer) string {
	return plain(l, "cli.probe.file")
}

// CliProbeInside Tree line: the elements this one appears inside; parents is a list.
type CliProbeInsideParams struct {
	Parents string
}

func CliProbeInside(l *i18n.Localizer, p CliProbeInsideParams) string {
	data := map[string]any{
		"Parents": p.Parents,
	}
	return withData(l, "cli.probe.inside", data)
}

// CliProbeMagic Probe field label: the container generation string.
func CliProbeMagic(l *i18n.Localizer) string {
	return plain(l, "cli.probe.magic")
}

// CliProbeNo Probe value: it was not.
func CliProbeNo(l *i18n.Localizer) string {
	return plain(l, "cli.probe.no")
}

// CliProbePayload Probe field label: the size of the plan XML inside it.
func CliProbePayload(l *i18n.Localizer) string {
	return plain(l, "cli.probe.payload")
}

// CliProbePayloadEncoding The payload size and the encoding it is in; size is the number.
type CliProbePayloadEncodingParams struct {
	Size string
}

func CliProbePayloadEncoding(l *i18n.Localizer, p CliProbePayloadEncodingParams) string {
	data := map[string]any{
		"Size": p.Size,
	}
	return withData(l, "cli.probe.payloadEncoding", data)
}

// CliProbeValueShape Tree table column: what type the attribute holds, never its value.
func CliProbeValueShape(l *i18n.Localizer) string {
	return plain(l, "cli.probe.valueShape")
}

// CliProbeYes Probe value: it was.
func CliProbeYes(l *i18n.Localizer) string {
	return plain(l, "cli.probe.yes")
}

// CliStatusAddress Status field label: the base URL the command asked.
func CliStatusAddress(l *i18n.Localizer) string {
	return plain(l, "cli.status.address")
}

// CliStatusApiVersion Status field label: the versioned namespace the server serves.
func CliStatusApiVersion(l *i18n.Localizer) string {
	return plain(l, "cli.status.apiVersion")
}

// CliStatusDependencyDown Status value: the server answers but something it needs does not.
func CliStatusDependencyDown(l *i18n.Localizer) string {
	return plain(l, "cli.status.dependencyDown")
}

// CliStatusDidNotAnswer Error returned when nothing is listening; address is the base URL.
type CliStatusDidNotAnswerParams struct {
	Address string
}

func CliStatusDidNotAnswer(l *i18n.Localizer, p CliStatusDidNotAnswerParams) string {
	data := map[string]any{
		"Address": p.Address,
	}
	return withData(l, "cli.status.didNotAnswer", data)
}

// CliStatusMinClient Status field label: the oldest client the server accepts.
func CliStatusMinClient(l *i18n.Localizer) string {
	return plain(l, "cli.status.minClient")
}

// CliStatusNo Status value: nothing answered on that address.
func CliStatusNo(l *i18n.Localizer) string {
	return plain(l, "cli.status.no")
}

// CliStatusNotAServer Error returned when the address answers with another product.
type CliStatusNotAServerParams struct {
	Address string
}

func CliStatusNotAServer(l *i18n.Localizer, p CliStatusNotAServerParams) string {
	data := map[string]any{
		"Address": p.Address,
	}
	return withData(l, "cli.status.notAServer", data)
}

// CliStatusNotGoptivum Status value when the address answers with something else; product is what it called itself.
type CliStatusNotGoptivumParams struct {
	Product string
}

func CliStatusNotGoptivum(l *i18n.Localizer, p CliStatusNotGoptivumParams) string {
	data := map[string]any{
		"Product": p.Product,
	}
	return withData(l, "cli.status.notGoptivum", data)
}

// CliStatusOtherApiVersion Status value when the server serves a version this build does not know; served is the server's, known is this build's.
type CliStatusOtherApiVersionParams struct {
	Known  string
	Served string
}

func CliStatusOtherApiVersion(l *i18n.Localizer, p CliStatusOtherApiVersionParams) string {
	data := map[string]any{
		"Known":  p.Known,
		"Served": p.Served,
	}
	return withData(l, "cli.status.otherApiVersion", data)
}

// CliStatusProduct Status field label: what the server says it is.
func CliStatusProduct(l *i18n.Localizer) string {
	return plain(l, "cli.status.product")
}

// CliStatusReached Status field label: whether anything answered at all.
func CliStatusReached(l *i18n.Localizer) string {
	return plain(l, "cli.status.reached")
}

// CliStatusReadiness Status field label: whether the server's dependencies answer.
func CliStatusReadiness(l *i18n.Localizer) string {
	return plain(l, "cli.status.readiness")
}

// CliStatusReady Status value: the server and everything it needs are up.
func CliStatusReady(l *i18n.Localizer) string {
	return plain(l, "cli.status.ready")
}

// CliStatusServerVersion Status field label: the build the server is running.
func CliStatusServerVersion(l *i18n.Localizer) string {
	return plain(l, "cli.status.serverVersion")
}

// CliStatusUnreachable Status value: the readiness probe itself could not be reached.
func CliStatusUnreachable(l *i18n.Localizer) string {
	return plain(l, "cli.status.unreachable")
}

// LogsConfigLoaded Log event: the configuration file was read and validated.
func LogsConfigLoaded(l *i18n.Localizer) string {
	return plain(l, "logs.configLoaded")
}

// LogsMigrationsApplied Log event: the database schema is at the version this build expects.
func LogsMigrationsApplied(l *i18n.Localizer) string {
	return plain(l, "logs.migrationsApplied")
}

// LogsNoIdentityProvider Log event: no Kratos is configured, so every route that needs a session stays unregistered rather than being mounted open.
func LogsNoIdentityProvider(l *i18n.Localizer) string {
	return plain(l, "logs.noIdentityProvider")
}

// LogsRunFailed Log event: the process is exiting because the work failed.
func LogsRunFailed(l *i18n.Localizer) string {
	return plain(l, "logs.runFailed")
}

// LogsServerStarted Log event: the HTTP server is listening.
func LogsServerStarted(l *i18n.Localizer) string {
	return plain(l, "logs.serverStarted")
}

// LogsServerStopping Log event: a signal arrived and the server stopped accepting.
func LogsServerStopping(l *i18n.Localizer) string {
	return plain(l, "logs.serverStopping")
}

// LogsStorageReady Log event: object storage answered, so documents can be written.
func LogsStorageReady(l *i18n.Localizer) string {
	return plain(l, "logs.storageReady")
}
