/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationsSwitcher: typeof import('./src/components/inputs/AnimationsSwitcher.vue')['default']
    Clock: typeof import('./src/components/outputs/Clock.vue')['default']
    Digit: typeof import('./src/components/outputs/Digit.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    LanguageSwitcher: typeof import('./src/components/inputs/LanguageSwitcher.vue')['default']
    Overlay: typeof import('./src/components/outputs/Overlay.vue')['default']
    ResourceButton: typeof import('./src/components/inputs/ResourceButton.vue')['default']
    ResourcePage: typeof import('./src/components/pages/ResourcePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTable: typeof import('./src/components/outputs/ScheduleTable.vue')['default']
    SettingsPage: typeof import('./src/components/pages/SettingsPage.vue')['default']
    ThemeSwitcher: typeof import('./src/components/inputs/ThemeSwitcher.vue')['default']
    Weather: typeof import('./src/components/outputs/Weather.vue')['default']
  }
}
