// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package config

import (
	"github.com/smegg99/s99config"
)

type Config struct {
	Application Application `json:"application"`

	Server Server `json:"server"`

	Storage Storage `json:"storage"`

	Logging Logging `json:"logging"`

	Security Security `json:"security"`

	Api API `json:"api"`
}

type Application struct {
	Name string `json:"name"`

	Environment string `json:"environment"`

	// What this program renders in: its log and what its command line prints.
	// A response never carries a sentence, only a key the desktop resolves in
	// the language the person reading it chose.
	Language string `json:"language"`
}

type Server struct {
	// 8833 keeps the habit of staying off the ports other stacks on a
	// development machine already own.
	Address string `json:"address"`

	ReadTimeoutSeconds int64 `json:"read_timeout_seconds"`

	WriteTimeoutSeconds int64 `json:"write_timeout_seconds"`

	IdleTimeoutSeconds int64 `json:"idle_timeout_seconds"`

	ShutdownTimeoutSeconds int64 `json:"shutdown_timeout_seconds"`

	// Who may set X-Forwarded-For. Omitted, this is loopback only, which is
	// where a reverse proxy sits. An explicit [] is read differently: apimount
	// then trusts nothing and uses the peer address.
	//
	// type=[]string: a defaulted open list generates as []any otherwise, which
	// does not match apiv1.Options.TrustedProxies.
	TrustedProxies []string `json:"trusted_proxies"`
}

type Storage struct {
	Database Database `json:"database"`

	Documents Documents `json:"documents"`
}

type Database struct {
	Driver string `json:"driver"`

	// A path for sqlite, a connection URL for postgres. The URL carries a
	// password, so it is a secret and never a command-line flag.
	DSN s99config.Secret `json:"dsn"`

	// Where sqlite puts its file when no DSN says otherwise.
	Path string `json:"path"`
}

// Documents live in a bucket by default and in a directory for a single-box or
// air-gapped school. An empty endpoint selects the directory.
type Documents struct {
	Endpoint string `json:"endpoint"`

	Bucket string `json:"bucket"`

	AccessKey s99config.Secret `json:"access_key"`

	SecretKey s99config.Secret `json:"secret_key"`

	UseSSL bool `json:"use_ssl"`

	Dir string `json:"dir"`
}

type Logging struct {
	Verbose bool `json:"verbose"`

	NoColor bool `json:"no_color"`

	EnableFiles bool `json:"enable_files"`

	Dir string `json:"dir"`

	Level string `json:"level"`

	MaxSizeMB int64 `json:"max_size_mb"`

	MaxBackups int64 `json:"max_backups"`

	MaxAgeDays int64 `json:"max_age_days"`

	LogName string `json:"log_name"`

	Compression string `json:"compression"`

	LocalTime bool `json:"local_time"`
}

type Security struct {
	// A plan endpoint carries a name and a school year, nothing more.
	MaximumBodyBytes int64 `json:"maximum_body_bytes"`

	// A real Optivum file is tens of kilobytes and a document about 25 KB
	// compressed, so this is headroom rather than a limit anyone meets.
	MaximumUploadBytes int64 `json:"maximum_upload_bytes"`

	// type=int: gengotypes defaults every CUE int to int64, and
	// apimount.Options.RateLimitPerMinute is a plain int.
	RateLimitPerMinute int `json:"rate_limit_per_minute"`
}

type API struct {
	// The oldest Goptivum Desktop this server accepts. Raising it turns away
	// clients that already work.
	MinClientVersion string `json:"min_client_version"`
}

type Environment string
