// common/config/embed.go

// Package config owns the server's configuration: its schema, its defaults and
// the types decoded from them.
package config

import _ "embed"

//go:generate go tool cue exp gengotypes ./...

// definition is the CUE schema s99config validates against. The Go types
// decoded from it live in cue_types_config_gen.go and are regenerated by
// just generate.
//
//go:embed config.cue
var definition []byte
